# JavaScript
[[plugins]]
repo = 'jelera/vim-javascript-syntax'
on_ft = 'js'

# HTML
[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

# CSS
[[plugines]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'